// <auto-generated />
using System;
using DineFlow.DataAccessObjects.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace DineFlow.DataAccessObjects.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("DineFlow.BusinessObjects.Auth.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("UserId");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Bills.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillId"));

                    b.Property<string>("BillCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("BillName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("BillNo")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CancelledBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<decimal>("DiscountAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("FinalAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsDefault")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("SubTotal")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("TableSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("BillId");

                    b.HasIndex("BillCode")
                        .IsUnique();

                    b.HasIndex("CancelledBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("TableSessionId")
                        .IsUnique()
                        .HasDatabaseName("UX_Bills_OneDefaultUnpaidBillPerSession")
                        .HasFilter("\"Status\" = 'Unpaid' AND \"IsDefault\" = TRUE");

                    b.HasIndex("TableSessionId", "BillNo")
                        .IsUnique()
                        .HasDatabaseName("UX_Bills_TableSessionId_BillNo_Active")
                        .HasFilter("\"Status\" <> 'Cancelled'");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Bills.BillDetail", b =>
                {
                    b.Property<int>("BillDetailId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BillDetailId"));

                    b.Property<int>("BillId")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerDisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ItemName")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("SessionCustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("BillDetailId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderItemId");

                    b.HasIndex("SessionCustomerId");

                    b.HasIndex("BillId", "SessionCustomerId");

                    b.ToTable("BillDetails");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Bills.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("BillId")
                        .HasColumnType("integer");

                    b.Property<string>("ChangeReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("ConfirmedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("PaidAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PaymentMethod")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("UpdatedBy")
                        .HasColumnType("integer");

                    b.HasKey("PaymentId");

                    b.HasIndex("BillId")
                        .IsUnique();

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex("UpdatedBy");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("CategoryName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("CategoryId");

                    b.HasIndex("CategoryName")
                        .IsUnique();

                    b.HasIndex("IsActive", "DisplayOrder");

                    b.ToTable("MenuCategories", null, t =>
                        {
                            t.HasCheckConstraint("CK_MenuCategories_DisplayOrder", "\"DisplayOrder\" >= 0");
                        });
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.ChoiceGroup", b =>
                {
                    b.Property<int>("ChoiceGroupId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChoiceGroupId"));

                    b.Property<int>("DefaultMaxSelect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("DefaultMinSelect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("ChoiceGroupId");

                    b.HasIndex("GroupName")
                        .IsUnique();

                    b.ToTable("ChoiceGroups", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChoiceGroups_DefaultMaxSelect", "\"DefaultMaxSelect\" >= \"DefaultMinSelect\" AND \"DefaultMaxSelect\" >= 1");

                            t.HasCheckConstraint("CK_ChoiceGroups_DefaultMinSelect", "\"DefaultMinSelect\" >= 0");
                        });
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.ChoiceItem", b =>
                {
                    b.Property<int>("ChoiceItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ChoiceItemId"));

                    b.Property<int>("ChoiceGroupId")
                        .HasColumnType("integer");

                    b.Property<string>("ChoiceName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<decimal>("ExtraPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int?>("LinkedMenuItemId")
                        .HasColumnType("integer");

                    b.HasKey("ChoiceItemId");

                    b.HasIndex("LinkedMenuItemId");

                    b.HasIndex("ChoiceGroupId", "ChoiceName")
                        .IsUnique();

                    b.HasIndex("ChoiceGroupId", "DisplayOrder");

                    b.ToTable("ChoiceItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChoiceItems_DisplayOrder", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_ChoiceItems_ExtraPrice", "\"ExtraPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.ChoiceItemChannelPrice", b =>
                {
                    b.Property<int>("ChoiceItemId")
                        .HasColumnType("integer");

                    b.Property<int>("SalesChannelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ChannelExtraPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("ChoiceItemId", "SalesChannelId");

                    b.HasIndex("SalesChannelId");

                    b.ToTable("ChoiceItemChannelPrices", null, t =>
                        {
                            t.HasCheckConstraint("CK_ChoiceItemChannelPrices_ExtraPrice", "\"ChannelExtraPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.MenuItem", b =>
                {
                    b.Property<int>("MenuItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MenuItemId"));

                    b.Property<int?>("AvailableQuantity")
                        .HasColumnType("integer");

                    b.Property<decimal>("BasePrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<bool>("CanOrderStandalone")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("ImageUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("IsAvailable")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("ItemType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<bool>("TrackStock")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("VisibilityStatus")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("MenuItemId");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.HasIndex("CategoryId", "Status", "VisibilityStatus", "DisplayOrder");

                    b.ToTable("MenuItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_MenuItems_AddonOnlyNotStandalone", "\"ItemType\" <> 'AddonOnly' OR \"CanOrderStandalone\" = FALSE");

                            t.HasCheckConstraint("CK_MenuItems_BasePrice", "\"BasePrice\" >= 0");

                            t.HasCheckConstraint("CK_MenuItems_DisplayOrder", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_MenuItems_StockNonNegative", "\"TrackStock\" = FALSE OR \"AvailableQuantity\" >= 0");

                            t.HasCheckConstraint("CK_MenuItems_TrackedStock", "\"TrackStock\" = FALSE OR \"AvailableQuantity\" IS NOT NULL");
                        });
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.MenuItemChannelPrice", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("SalesChannelId")
                        .HasColumnType("integer");

                    b.Property<decimal>("ChannelExtraPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.HasKey("MenuItemId", "SalesChannelId");

                    b.HasIndex("SalesChannelId");

                    b.ToTable("MenuItemChannelPrices", null, t =>
                        {
                            t.HasCheckConstraint("CK_MenuItemChannelPrices_ExtraPrice", "\"ChannelExtraPrice\" >= 0");
                        });
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.MenuItemChoiceGroup", b =>
                {
                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<int>("ChoiceGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("DisplayOrder")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsRequired")
                        .HasColumnType("boolean");

                    b.Property<int>("MaxSelect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("MinSelect")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.HasKey("MenuItemId", "ChoiceGroupId");

                    b.HasIndex("ChoiceGroupId");

                    b.HasIndex("MenuItemId", "DisplayOrder");

                    b.ToTable("MenuItemChoiceGroups", null, t =>
                        {
                            t.HasCheckConstraint("CK_MenuItemChoiceGroups_DisplayOrder", "\"DisplayOrder\" >= 0");

                            t.HasCheckConstraint("CK_MenuItemChoiceGroups_MaxSelect", "\"MaxSelect\" >= 1");

                            t.HasCheckConstraint("CK_MenuItemChoiceGroups_MinSelect", "\"MinSelect\" >= 0 AND \"MinSelect\" <= \"MaxSelect\"");

                            t.HasCheckConstraint("CK_MenuItemChoiceGroups_RequiredMinSelect", "\"IsRequired\" = FALSE OR \"MinSelect\" >= 1");
                        });
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.SalesChannel", b =>
                {
                    b.Property<int>("SalesChannelId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SalesChannelId"));

                    b.Property<string>("ChannelCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.HasKey("SalesChannelId");

                    b.HasIndex("ChannelCode")
                        .IsUnique();

                    b.ToTable("SalesChannels", (string)null);
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Orders.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderId"));

                    b.Property<string>("CancelReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<DateTime?>("CancelledAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CancelledBy")
                        .HasColumnType("integer");

                    b.Property<string>("ClientToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CreatedBy")
                        .HasColumnType("integer");

                    b.Property<string>("CustomerNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("ExternalOrderCode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("OrderCode")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("OrderSource")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("PrintError")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("PrintRetryCount")
                        .HasColumnType("integer");

                    b.Property<string>("PrintStatus")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime?>("PrintedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("SalesChannelId")
                        .HasColumnType("integer");

                    b.Property<int?>("SessionCustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("SystemNote")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("TableSessionId")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderId");

                    b.HasIndex("CancelledBy");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("ExternalOrderCode")
                        .HasFilter("\"ExternalOrderCode\" IS NOT NULL");

                    b.HasIndex("OrderCode")
                        .IsUnique();

                    b.HasIndex("SalesChannelId");

                    b.HasIndex("SessionCustomerId");

                    b.HasIndex("TableSessionId");

                    b.ToTable("Orders", (string)null);
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Orders.OrderItem", b =>
                {
                    b.Property<int>("OrderItemId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemId"));

                    b.Property<decimal>("BasePriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("ChannelExtraPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("FinalUnitPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("MenuItemId")
                        .HasColumnType("integer");

                    b.Property<string>("MenuItemNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Note")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("OrderId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.Property<int?>("SessionCustomerId")
                        .HasColumnType("integer");

                    b.Property<decimal>("TotalPrice")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("OrderItemId");

                    b.HasIndex("MenuItemId");

                    b.HasIndex("OrderId");

                    b.HasIndex("SessionCustomerId");

                    b.ToTable("OrderItems", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItems_Prices", "\"BasePriceSnapshot\" >= 0 AND \"ChannelExtraPriceSnapshot\" >= 0 AND \"FinalUnitPriceSnapshot\" >= 0");

                            t.HasCheckConstraint("CK_OrderItems_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Orders.OrderItemSelectedChoice", b =>
                {
                    b.Property<int>("OrderItemSelectedChoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OrderItemSelectedChoiceId"));

                    b.Property<decimal>("ChannelExtraPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<int>("ChoiceGroupId")
                        .HasColumnType("integer");

                    b.Property<int>("ChoiceItemId")
                        .HasColumnType("integer");

                    b.Property<string>("ChoiceNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("ExtraPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<decimal>("FinalExtraPriceSnapshot")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("GroupNameSnapshot")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("OrderItemId")
                        .HasColumnType("integer");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("OrderItemSelectedChoiceId");

                    b.HasIndex("ChoiceGroupId");

                    b.HasIndex("ChoiceItemId");

                    b.HasIndex("OrderItemId");

                    b.ToTable("OrderItemSelectedChoices", null, t =>
                        {
                            t.HasCheckConstraint("CK_OrderItemSelectedChoices_Prices", "\"ExtraPriceSnapshot\" >= 0 AND \"ChannelExtraPriceSnapshot\" >= 0 AND \"FinalExtraPriceSnapshot\" >= 0");

                            t.HasCheckConstraint("CK_OrderItemSelectedChoices_Quantity", "\"Quantity\" > 0");
                        });
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Requests.ServiceRequest", b =>
                {
                    b.Property<int>("RequestId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RequestId"));

                    b.Property<string>("ClientToken")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("CompletedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("ConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("ConfirmedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Message")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("PaymentMethod")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Reason")
                        .HasMaxLength(255)
                        .HasColumnType("character varying(255)");

                    b.Property<string>("RequestType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int?>("SessionCustomerId")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TableSessionId")
                        .HasColumnType("integer");

                    b.HasKey("RequestId");

                    b.HasIndex("CompletedBy");

                    b.HasIndex("ConfirmedBy");

                    b.HasIndex("SessionCustomerId");

                    b.HasIndex("RequestType", "Status");

                    b.HasIndex("TableSessionId", "Status");

                    b.ToTable("ServiceRequests");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Tables.DiningTable", b =>
                {
                    b.Property<int>("TableId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TableId"));

                    b.Property<string>("Area")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("QrToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("TableName")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("TableId");

                    b.HasIndex("QrToken")
                        .IsUnique();

                    b.ToTable("DiningTables");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Tables.TableSession", b =>
                {
                    b.Property<int>("TableSessionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TableSessionId"));

                    b.Property<int?>("ClosedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("EndedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("OpenedBy")
                        .HasColumnType("integer");

                    b.Property<DateTime>("StartedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("TableId")
                        .HasColumnType("integer");

                    b.HasKey("TableSessionId");

                    b.HasIndex("ClosedBy");

                    b.HasIndex("OpenedBy");

                    b.HasIndex("TableId")
                        .IsUnique()
                        .HasDatabaseName("UX_TableSessions_OneOpenSessionPerTable")
                        .HasFilter("\"Status\" IN ('Open', 'WaitingPayment')");

                    b.ToTable("TableSessions");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Tables.TableSessionCustomer", b =>
                {
                    b.Property<int>("SessionCustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SessionCustomerId"));

                    b.Property<string>("ClientToken")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("TableSessionId")
                        .HasColumnType("integer");

                    b.HasKey("SessionCustomerId");

                    b.HasIndex("TableSessionId", "ClientToken")
                        .IsUnique();

                    b.ToTable("TableSessionCustomers");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Bills.Bill", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Auth.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DineFlow.BusinessObjects.Auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DineFlow.BusinessObjects.Tables.TableSession", "TableSession")
                        .WithMany("Bills")
                        .HasForeignKey("TableSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CancelledByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("TableSession");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Bills.BillDetail", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Bills.Bill", "Bill")
                        .WithMany("BillDetails")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Menu.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Orders.OrderItem", "OrderItem")
                        .WithMany()
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Tables.TableSessionCustomer", "SessionCustomer")
                        .WithMany()
                        .HasForeignKey("SessionCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bill");

                    b.Navigation("MenuItem");

                    b.Navigation("OrderItem");

                    b.Navigation("SessionCustomer");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Bills.Payment", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Bills.Bill", "Bill")
                        .WithOne("Payment")
                        .HasForeignKey("DineFlow.BusinessObjects.Bills.Payment", "BillId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Auth.User", "ConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Auth.User", "UpdatedByUser")
                        .WithMany()
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Bill");

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.ChoiceItem", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Menu.ChoiceGroup", "ChoiceGroup")
                        .WithMany("ChoiceItems")
                        .HasForeignKey("ChoiceGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Menu.MenuItem", "LinkedMenuItem")
                        .WithMany("UsedAsLinkedChoiceItems")
                        .HasForeignKey("LinkedMenuItemId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("ChoiceGroup");

                    b.Navigation("LinkedMenuItem");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.ChoiceItemChannelPrice", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Menu.ChoiceItem", "ChoiceItem")
                        .WithMany("ChannelPrices")
                        .HasForeignKey("ChoiceItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Menu.SalesChannel", "SalesChannel")
                        .WithMany("ChoiceItemPrices")
                        .HasForeignKey("SalesChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoiceItem");

                    b.Navigation("SalesChannel");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.MenuItem", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Menu.Category", "Category")
                        .WithMany("MenuItems")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Category");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.MenuItemChannelPrice", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Menu.MenuItem", "MenuItem")
                        .WithMany("ChannelPrices")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Menu.SalesChannel", "SalesChannel")
                        .WithMany("MenuItemPrices")
                        .HasForeignKey("SalesChannelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MenuItem");

                    b.Navigation("SalesChannel");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.MenuItemChoiceGroup", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Menu.ChoiceGroup", "ChoiceGroup")
                        .WithMany("MenuItems")
                        .HasForeignKey("ChoiceGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Menu.MenuItem", "MenuItem")
                        .WithMany("ChoiceGroups")
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoiceGroup");

                    b.Navigation("MenuItem");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Orders.Order", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Auth.User", "CancelledByUser")
                        .WithMany()
                        .HasForeignKey("CancelledBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DineFlow.BusinessObjects.Auth.User", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DineFlow.BusinessObjects.Menu.SalesChannel", "SalesChannel")
                        .WithMany()
                        .HasForeignKey("SalesChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Tables.TableSessionCustomer", "SessionCustomer")
                        .WithMany()
                        .HasForeignKey("SessionCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DineFlow.BusinessObjects.Tables.TableSession", "TableSession")
                        .WithMany("Orders")
                        .HasForeignKey("TableSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CancelledByUser");

                    b.Navigation("CreatedByUser");

                    b.Navigation("SalesChannel");

                    b.Navigation("SessionCustomer");

                    b.Navigation("TableSession");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Orders.OrderItem", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Menu.MenuItem", "MenuItem")
                        .WithMany()
                        .HasForeignKey("MenuItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Orders.Order", "Order")
                        .WithMany("OrderItems")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Tables.TableSessionCustomer", "SessionCustomer")
                        .WithMany()
                        .HasForeignKey("SessionCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MenuItem");

                    b.Navigation("Order");

                    b.Navigation("SessionCustomer");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Orders.OrderItemSelectedChoice", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Menu.ChoiceGroup", "ChoiceGroup")
                        .WithMany()
                        .HasForeignKey("ChoiceGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Menu.ChoiceItem", "ChoiceItem")
                        .WithMany()
                        .HasForeignKey("ChoiceItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("DineFlow.BusinessObjects.Orders.OrderItem", "OrderItem")
                        .WithMany("SelectedChoices")
                        .HasForeignKey("OrderItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChoiceGroup");

                    b.Navigation("ChoiceItem");

                    b.Navigation("OrderItem");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Requests.ServiceRequest", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Auth.User", "CompletedByUser")
                        .WithMany()
                        .HasForeignKey("CompletedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DineFlow.BusinessObjects.Auth.User", "ConfirmedByUser")
                        .WithMany()
                        .HasForeignKey("ConfirmedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DineFlow.BusinessObjects.Tables.TableSessionCustomer", "SessionCustomer")
                        .WithMany()
                        .HasForeignKey("SessionCustomerId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DineFlow.BusinessObjects.Tables.TableSession", "TableSession")
                        .WithMany("ServiceRequests")
                        .HasForeignKey("TableSessionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CompletedByUser");

                    b.Navigation("ConfirmedByUser");

                    b.Navigation("SessionCustomer");

                    b.Navigation("TableSession");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Tables.TableSession", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Auth.User", "ClosedByUser")
                        .WithMany()
                        .HasForeignKey("ClosedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DineFlow.BusinessObjects.Auth.User", "OpenedByUser")
                        .WithMany()
                        .HasForeignKey("OpenedBy")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("DineFlow.BusinessObjects.Tables.DiningTable", "Table")
                        .WithMany("TableSessions")
                        .HasForeignKey("TableId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ClosedByUser");

                    b.Navigation("OpenedByUser");

                    b.Navigation("Table");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Tables.TableSessionCustomer", b =>
                {
                    b.HasOne("DineFlow.BusinessObjects.Tables.TableSession", "TableSession")
                        .WithMany("Customers")
                        .HasForeignKey("TableSessionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("TableSession");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Bills.Bill", b =>
                {
                    b.Navigation("BillDetails");

                    b.Navigation("Payment");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.Category", b =>
                {
                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.ChoiceGroup", b =>
                {
                    b.Navigation("ChoiceItems");

                    b.Navigation("MenuItems");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.ChoiceItem", b =>
                {
                    b.Navigation("ChannelPrices");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.MenuItem", b =>
                {
                    b.Navigation("ChannelPrices");

                    b.Navigation("ChoiceGroups");

                    b.Navigation("UsedAsLinkedChoiceItems");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Menu.SalesChannel", b =>
                {
                    b.Navigation("ChoiceItemPrices");

                    b.Navigation("MenuItemPrices");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Orders.Order", b =>
                {
                    b.Navigation("OrderItems");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Orders.OrderItem", b =>
                {
                    b.Navigation("SelectedChoices");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Tables.DiningTable", b =>
                {
                    b.Navigation("TableSessions");
                });

            modelBuilder.Entity("DineFlow.BusinessObjects.Tables.TableSession", b =>
                {
                    b.Navigation("Bills");

                    b.Navigation("Customers");

                    b.Navigation("Orders");

                    b.Navigation("ServiceRequests");
                });
#pragma warning restore 612, 618
        }
    }
}
